### PR TITLE
feat: protocol v1.20

### PR DESCRIPTION
**Pull request by zinserjan**
This adds support for procotol v1.05 like before.

I tested it against my Growatt MIC 1000TL-X.

Edit: Temperature 3093 doesn't exist in 1.05, but in higher versions... so still a WIP

### CODE REVIEW

**Comment by tommarek** [comment]
regarding the temperature 3093 register. According to the Growatt documentation following register ranges are available based on the used device:

**L-X/TL-XH/TL-XH US（MIN Type）**：
 - 03 register range: 0-124, 3000-3124，3125-3249(TL-XHUS) 
 - 04 register range: 3000-3124, 3125-3249，3250-3374（TL-XH

**TL3-X(MAX、MID、MAC Type)**
 - 03 register range: 0-124, 125-249
 - 04 register range: 0-124, 125-249
 
**MAX 1500V、MAX-X LV**:
 - 03 register range: 0-124, 125-249
 - 04 register range: 0-124, 125-249, 875-999
 
**MOD TL3-XH:**
 - 03 register range: 0-124, 3000-3124
 - 04 register range: 3000-3124, 3125-3249
 
**Storage(MIX Type)**：
 - 03 register range: 0-124, 1000-1124
 - 04 register range: 0-124, 1000-1124

**Storage(SPA Type)**：
 - 03 register range: 0-124, 1000-1124
 - 04 register range: 1000-1124, 2000-2124, 1125-1249
 
**Storage(SPH Type)**：
 - 03 register range: 0-124, 1000-1124
 - 04 register range: 0-124, 1000-1124, 1125-1249

Anything outside of these ranges will fail to read/write. So it's not only about the protocol version but a type of the inverter as well,

**Comment by zinserjan** [comment]
Ah good to know. Makes sense.

**Comment by tommarek** [comment]
are you going to make some changes to the PR? :)( I've changed the way we load the protocol from growatt.cpp in one of the latest commits so make sure to adapt to that please)

**Comment by zinserjan** [comment]
Yeah, but the problem is to identify the correct version number. It's not v1.05 because 3093 isn't documented there. It could be 1.20, but I'm just guessing. Do you know how I can find out which protocol version is being used?

Reading the modbus version via holding register 88 returns 305 for me, but the 3.05 protocol doesn't work for me :D 

Maybe it's better to do this stuff device specific instead, but this only works when the protocol doesn't change (e.g. firmware update) in the future.

**Comment by tommarek** [comment]
Yeah, it gives me 305 as well. I got this protocol specification from the company that sold me the inverter, so I hope it should be right. Hard to say what the best solution here would be. I think if it fits the 1.20 definition (all registers that you're addressing match the protocol specification document) then just call it 1.20. In the end we can't support all devices and all protocols given how little info there is on the internet...

**Comment by zinserjan** [comment]
Ok, then I'll rename it to 120 and add a note that I'm using this for the TL-X.

**Comment by zinserjan** [comment]
Unfortunately, the sun has already gone down, so I have to test this tomorrow.

**Comment by tommarek** [comment]
I've compared it to 1.20 and it matches perfectly! thanks! :) please test it and once you do I'll merge it to my branch :)

**Comment by zinserjan** [comment]
AcOutputCurrent seems to be wrong. Everything else is OK...
````
{
    "InverterStatus": 1,
    "DcPower": 85.7,
    "DcVoltage": 117.4,
    "DcInputCurrent": 0.8,
    "AcFrequency": 50.01,
    "AcVoltage": 235.8,
    "AcOutputCurrent": 1.2,
    "AcPower": 85.6,
    "EnergyToday": 0.1,
    "EnergyTotal": 711,
    "OperatingTime": 1.1491608e7,
    "Temperature": 32.9,
    "OnOff": 1,
    "CmcMemoryState": 0,
    "ActivePowerRate": 100,
    "Mac": "A8:48:FA:C9:4B:EB",
    "Cnt": 52
}
````


EDIT: At least not an rounding issue:

```
{
    "InverterStatus": 1,
    "DcPower": 75,
    "DcVoltage": 115.3000031,
    "DcInputCurrent": 0.699999988,
    "AcFrequency": 50,
    "AcVoltage": 235,
    "AcOutputCurrent": 1.200000048,
    "AcPower": 75.80000305,
    "EnergyToday": 0.100000001,
    "EnergyTotal": 711,
    "OperatingTime": 1.1492232e7,
    "Temperature": 32.90000153,
    "OnOff": 1,
    "CmcMemoryState": 0,
    "ActivePowerRate": 100,
    "Mac": "A8:48:FA:C9:4B:EB",
    "Cnt": 30
}
```

EDIT2: All other registers for Iac1 returning the same values. I thought it was correct in the past, but with more power. At the moment there is absolutely no sun and pretty cloudy...

**Comment by tommarek** [comment]
yeah please make sure to compare the value with the value you get when reading the register directly from the UI.

**Comment by zinserjan** [comment]
Reading it directly via the UI returns the same value. That's how I tested all Iac1 values/registers.

Btw  this looks much better with more power:

```json
{
"InverterStatus": 1,
"DcPower": 852.7999878,
"DcVoltage": 119.3000031,
"DcInputCurrent": 7.200000286,
"AcFrequency": 50.02999878,
"AcVoltage": 236.8000031,
"AcOutputCurrent": 3.5,
"AcPower": 853.2000122,
"EnergyToday": 0.300000012,
"EnergyTotal": 711.2000122,
"OperatingTime": 11498472,
"Temperature": 35.60000229,
"OnOff": 1,
"CmcMemoryState": 0,
"ActivePowerRate": 100,
"Mac": "A8:48:FA:C9:4B:EB",
"Cnt": 30
}
```

Seems to be some kind of bug in the inverter itself. 
I would either keep it as it is is or remove the reading.

**Comment by tommarek** [comment]
Looks good to me, thanks! Will merge it this evening :-)

**Comment by zinserjan** [comment]
It seems to work now, but I have no idea why the values were completely wrong in the morning...

Anyway. I would like to change the whole config again and enhance it to support the larger Growatt TL-X/H inverters. Reading PV2 and three phase register even works for my inverter and reports 0 as expected.

**Comment by zinserjan** [comment]
Seems to work pretty good. I just used your 1.24 as template, which seems to be pretty identical for 0 ~124 (or at least for the registers I used). 

I renamed some of the properties, like the whole grid stuff, to group them more togehter.

```json
{
"InverterStatus": 1,
"InputPower": 583.1,
"PV1Voltage": 109.8,
"PV1InputPower": 583.1,
"PV1InputCurrent": 5.8,
"PV2Voltage": 0,
"PV2InputPower": 0,
"PV2InputCurrent": 0,
"OutputPower": 585.6,
"GridFrequency": 49.98,
"GridL1Voltage": 232.5,
"GridL1OutputCurrent": 2.7,
"GridL1OutputPower": 646.4,
"GridL2Voltage": 0,
"GridL2OutputCurrent": 0,
"GridL2OutputPower": 0,
"GridL3Voltage": 0,
"GridL3OutputCurrent": 0,
"GridL3OutputPower": 0,
"EnergyToday": 1,
"EnergyTotal": 713.5,
"WorkTimeTotal": 11536530,
"PV1EnergyToday": 1,
"PV1EnergyTotal": 722.4,
"PV2EnergyToday": 0,
"PV2EnergyTotal": 0,
"PVEnergyTotal": 722.4,
"InverterTemperature": 40.3,
"InverterIPMTemperature": 40.3,
"OnOff": 1,
"CmdMemoryState": 0,
"ActivePowerRate": 100,
"Mac": "A8:48:FA:C9:4B:EB",
"Cnt": 162
}
```


image

**Comment by zinserjan** [comment]
Added a `clang-format` file and also `.editorconfig`. 

I tried some settings that the code will look more like before, but it's kinda hard due to the different formatting settings.

**Comment by tommarek** [comment]
I'm no cpp developer so i don't have a set ways of code formatting. I think we should really take this to otti and then do a big refactoring commit that would clean the entire project up.

**Comment by zinserjan** [comment]
Ok, it's gone ;)

**Comment by tommarek** [comment]
if you're happy with this I will merge it to my branch :)

**Comment by zinserjan** [comment]
Yeah, let's go :)

**Pull request merged**
